openapi: "3.0.0"
info:
  description: "Profiler service, responsible for showing metrics of the chats in the application"
  version: "0.0.1" 
  title: "profile-service"

servers: 
  - url: "http://localhost:8810"
tags:
  - name: "profiler"
    description: "Operations about the profilers"
  - name: "metrics"
    description: "Operations metrics"

paths:
  /profiler:
    x-router-controller: routes.config
    post:
      operationId: addProfiler
      summary: "Creates new profiler"
      tags: 
        - profiler

      responses:
        201:
          description: "Profiler added successfully"

        500:
          description: Internal server error

  /profiler/{profilerID}:
    x-router-controller: routes.config
    get:
      operationId: getProfiler
      summary: "Get profiler data"
      tags: 
        - profiler

      parameters:
        - in: path
          name: profilerID
          required: true
          schema:
            type: string

      responses:
        200:
          description: "Profiler info"

        500:
          description: Internal server error

    put:
      operationId: updateProfiler
      summary: "Update profiler data"
      tags: 
        - profiler

      parameters:
        - in: path
          name: profilerID
          required: true
          schema:
            type: string

      responses:
        200:
          description: "Profiler data updated"

        500:
          description: Internal server error

    delete:
      operationId: removeProfiler
      summary: "Remove profiler"
      tags: 
        - profiler

      parameters:
      - in: path
        name: profilerID
        required: true
        schema:
          type: string

      responses:
        200:
          description: "Profiler removed successfully"

        500:
          description: Internal server error

  /health:
    x-router-controller: routes.config
    get:
      operationId: healthRoute
      summary: "Check server's avilablity"
      responses:
        "200":
          description: "Response OK"

  
        
# securityDefinitions:
#   petstore_auth:
#     type: "oauth2"
#     authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
#     flow: "implicit"
#     scopes:
#       write:pets: "modify pets in your account"
#       read:pets: "read your pets"
#   api_key:
#     type: "apiKey"
#     name: "api_key"
#     in: "header"