openapi: "3.0.0"
info:
  description: "RealTime firebase based chat service"
  version: "0.0.1" 
  title: "chat-service"

servers: 
  - url: "http://localhost:8810"
tags:
  - name: "channels"
    description: "Operations about user"

paths:
  /channels:
    x-router-controller: routes.config
    get:
      tags:
        - channels
      
      operationId: getAvailableChannels_R
      summary: Test request for checking the user component, don't forget to change it or delete it
      responses:
        200:
          description: "Request ran successfuly"

  /channel:
    x-router-controller: routes.config
    post:
      tags:
        - channels
      
      operationId: createChannel_R
      summary: Add new channel

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Channel'

      responses:
        201:
          description: 'Channel created successfully'
        
        500:
          description: 'Internal server error'

  /channel/{channelID}:
    x-router-controller: routes.config
    get:
      tags:
        - channels
      
      operationId: getChannelByID_R
      summary: Get channel info by it's id

      parameters:
        - in: path
          name: channelID
          required: true
          schema:
            type: string

      responses:
        200: 
          description: 'channel info'
        
        500:
          description: 'Internal server error'

    put:
      tags:
        - channels

      operationId: editChannelByID_R
      summary: Edit existing channel by it's ID

      parameters:
        - in: path
          name: channelID
          required: true
          schema:
            type: string

      responses:
        200: 
          description: 'Channel updated successfully'
        
        500:
          description: 'Internal server error'

    delete:
      tags:
        - channels

      operationId: deleteChannelByID_R
      summary: Delete channel by it's ID

      parameters:
        - in: path
          name: channelID
          required: true
          schema:
            type: string

      responses:
        200:
          description: Delete succeeded

        500:
          description: Internal server error

  /channel/{channelID}/message:
    x-router-controller: routes.config
    post:
      tags:
        - channels
        
      operationId: postNewMessage_R
      summary: Post new message into a channel
      parameters:
        - in: path
          name: channelID
          required: true
          schema:
            type: string

      responses:
        201:
          description: 'Message sent successfully'
        
        500:
          description: 'Internal server error'

  /health:
    x-router-controller: routes.config
    get:
      operationId: health_R
      summary: "Check server's avilablity"
      responses:
        200:
          description: "Response OK"

components:
  schemas:
    Channel:
      type: object
      required:
        - name

      properties:
        name:
          type: string
        profileImageURL: 
          type: string
        info: 
          type: string